; PlatformIO project configuration - BCA182 Laboratory Activity 1
; PART I: Project Initialization
; The framework is EXPLICITLY stm32cube (Arduino framework is not permitted
; for this laboratory).
[platformio]
default_envs = bluepill_f103c8

[env:bluepill_f103c8]
platform = ststm32@20.0.0
board = bluepill_f103c8
framework = stm32cube
monitor_speed = 115200
